import exp from "constants"

export type {IconProps} from "./type"
export type {IconName} from "./type"

export {IconElements} from './constants'

export {ArrowIcon} from "./arrow"
export {BellIcon} from "./bell"
export {CalendarIcon} from "./calendar"
export {CheckmarkIcon} from "./checkmark"
export {CommentIcon} from "./comment"
export {EditIcon} from "./edit"
export {EmailIcon} from "./email"
export {ExitIcon} from "./exit"
export {FilterIcon} from "./filter"
export {GarbageIcon} from "./garbage"
export {LogoIcon} from "./logo"
export {PasswordIcon} from "./password"
export {PenIcon} from "./pen"
export {PhoneIcon} from "./phone"
export {PlusIcon} from "./plus"
export {RhombIcon} from "./rhomb"
export {TGIcon} from "./tg"
export {UserIcon} from "./user"
export {LensIcon} from "./lens"
export {EyeIcon} from "./eye"
export {SaveIcon} from "./save"
export {PointsIcon} from "./points"
export {SunIcon} from "./sun"
export {PhotoIcon} from "./photo"

